#! /usr/bin/env bash

[ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"


expect_text()
{
   local filename="$1"
   local text="$2"

   if ! pattern_matches_relative_filename "${pattern}" "${text}"
   then
      fail "Pattern \"${pattern}\" did not match text \"${text}\""
   fi
}


main()
{
   MULLE_C_SOURCETREE_UPDATE_FLAGS="$@"

   _options_mini_main "$@"

   remove_file_if_present "src/dependencies.h"
   mkdir_if_missing src

   MULLE_SOURCETREE_FLAGS="-e" ; export MULLE_SOURCETREE_FLAGS
   exekutor "${MULLE_C_SOURCETREE_UPDATE}" ${MULLE_C_SOURCETREE_UPDATE_FLAGS}  || exit 1

   if ! diffs="`diff -q "dependencies.h.expect" src/dependencies.h`"
   then
      log_error "unexpected output"
      echo "${diffs}"
      exit 1
   fi

   log_info "----- ALL PASSED -----"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_C_SOURCETREE_UPDATE="${MULLE_C_SOURCETREE_UPDATE:-${PWD}/../../mulle-c-sourcetree-update}"
}


init "$@"
main "$@"

