/* This file will be regenerated by `mulle-sde update|monitor`. Edits will be lost.
#ifndef _01_sourcetree_dependencies_h__
#define _01_sourcetree_dependencies_h__

# include <mulle-thread/mulle-thread.h>

# if ! defined( __APPLE__) && ! defined( __FREEBSD__)
#  include <mulle-allocator/mulle-allocator.h>
# endif

# if defined( __APPLE__)
#  include <mulle-concurrent/mulle-concurrent.h>
# endif

# include <foo/foo.h>

#endif
